# Generated by Django 5.2.17 on 2026-10-01 10:13

import django.db.models.deletion
import trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "share_code",
                    models.CharField(
                        default=trips.models.generate_share_code,
                        editable=False,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paise", models.PositiveBigIntegerField()),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="trips.group",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("upi_id", models.CharField(max_length=321)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="trips.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("share_paise", models.PositiveBigIntegerField()),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="trips.expense",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_shares",
                        to="trips.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="paid_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses_paid",
                to="trips.member",
            ),
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paise", models.PositiveBigIntegerField()),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements_paid",
                        to="trips.member",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="trips.group",
                    ),
                ),
                (
                    "to_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements_received",
                        to="trips.member",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("group", "name"), name="unique_member_name_per_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseshare",
            constraint=models.UniqueConstraint(
                fields=("expense", "member"), name="unique_member_per_expense"
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paise__gt", 0)),
                name="expense_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paise__gt", 0)),
                name="settlement_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_member", models.F("to_member")), _negated=True
                ),
                name="settlement_from_ne_to",
            ),
        ),
    ]
